### ISSUE TITLE
is there any way to upgrade to newer pytorch version

### ISSUE THREAD

**Issue by pardont** [arunmallya/packnet#4]
hi @arunmallya ，I try to run script 
./scripts/run_lwf.sh csf ../checkpoints/imagenet/vgg16.pt 2,3

seems vgg16.pt file  worked with pytorch  0.2.0.post3,  and can download from 
https://uofi.box.com/s/zap2p03tnst9dfisad4u0sfupc0y1fxt

is there any way to upgrade to newer pytorch version, such as pytorch 1.6

Thanks

**Comment by arunmallya** [comment]
Hi, I am not actively maintaining this at the moment. 
You can try using a newer pytorch version and fixing issues as they come along. 
If you can get it to work, please feel free to send a merge request.
